### ISSUE TITLE
ERORRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

### ISSUE THREAD

**Issue by yurrii22** [SlowPotato/Aimmy-GPU-ENABLE-Tutorial#1]
a fucking big ass error every single time i type this yolo task=detect mode=train imgsz=640 data=data.yaml epochs=1000 batch=16 name=Dayz and i did all the steps 5 times still the same shit
![image](https://github.com/SlowPotato/Aimmy-GPU-ENABLE-Tutorial/assets/155194262/96aa708d-3157-42e0-9299-f3b6d791c366)

**Comment by yurrii22** [comment]
ALSO THIS SHIT STEP DIDNT WORK AND I DIDNT UNDERSTAND IT 
![image](https://github.com/SlowPotato/Aimmy-GPU-ENABLE-Tutorial/assets/155194262/79255cc3-3da8-4362-93ef-d20e672b381f)

**Comment by SlowPotato** [comment]
Reach out to me via discord my guy...

Sent via the Samsung Galaxy Note20 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SlowPotato** [comment]
Everyone who has followed the tutorial has gotten or fixed Gpu errors or enabled GPU for training.

**Comment by SlowPotato** [comment]
> a fucking big ass error every single time i type this yolo task=detect mode=train imgsz=640 data=data.yaml epochs=1000 batch=16 name=Dayz and i did all the steps 5 times still the same shit ![image](https://private-user-images.githubusercontent.com/155194262/313493369-96aa708d-3157-42e0-9299-f3b6d791c366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjA5OTEsIm5iZiI6MTcxMDcyMDY5MSwicGF0aCI6Ii8xNTUxOTQyNjIvMzEzNDkzMzY5LTk2YWE3MDhkLTMxNTctNDJlMC05Mjk5LWYzYjZkNzkxYzM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMDExMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTAwODUzMDM5MWNkMDZiZDE5MjkwNDVmYzJkMzI5NDRhODk0YjkxYWU5NzU3NWM1YWQ3NTA5NzVjNThkOTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DMc0YFN2lwHjQRVcqBtTHhBJkuRhwNUlqnTPC1BFoU4)

My guy... you dont have your data.yaml file in the root of your folder thats why its not working...
![Screenshot_20240317_123949_Chrome](https://github.com/SlowPotato/Aimmy-GPU-ENABLE-Tutorial/assets/152599873/5045f689-4c86-476e-abff-7ef517c136d6)

**Comment by SlowPotato** [comment]
Please follow steps regards to data.yaml file and you should have issue resolved, this is not a tutorial error its a user error.

**Comment by yurrii22** [comment]
yurrii
 add me on discord bro
we need to talk i really really want to learn well

**Comment by yurrii22** [comment]
yesterday i fixed the erorr but today i got another so i really need to ask you about stuff send me rq or give me urs

**Comment by SlowPotato** [comment]
Discord# MentalEngineer#4729

Sent via the Samsung Galaxy Note20 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yurrii22** [comment]
aight mate ill send now
